language: python
python:
- "3.8"
before_install:
    - pip install pytest pytest-cov pytest-pep8
    - pip install python-coveralls coverage
    - pip install nose
script:
  - pytest -v --cov=validated_dc tests
after_success:
  - coveralls
